# This is a basic workflow to help you get started with Actions

name: Create a comment on new issues

# Controls when the workflow will run
on:
  issues:
      types: [opened]
jobs:
  comment_with_action:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: "dump github context"
        run: echo '${{ toJSON{github.event} }}' | jq
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number}}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
